/*******************************************************************************
            Macro name: lsload
              Location: <SASCONFIGDIR>/LevN/SASApp/SASEnvironment/SASMacro
            Written by: Dave Glemaker, David.Glemaker@sas.com.
         Creation date: Jan 18 2017.
            As of date: April 08 2020.
           SAS version: SAS 9.4M4 SAS Grid Manager
               Purpose: List and Graph Grid Host with thier loads
                 Usage: %lsload
            Parameters: none
   Optional Parameters: none
     Data sets created: work.lsload work.temp work.temp1
File Reference created: lsload
           Limitations:
                 Notes: requires xcmd turned on and LSF configured
               History: 04/08/2020 Dave Glemaker added Documentation
                        04/08/2020 Dave Glemaker added Disclaimer
     Sample Macro call: %lsload
This macro is made available “as is” and disclaims any and all representations
and warranties, including without limitation, implied warranties of
merchantability, accuracy, and fitness for a particular purpose.
*********************************************************************************/
%macro lsload;
options spool;
filename lsload pipe "lsload";
data lsload;
   infile lsload firstobs=2 dlm=" ";
   length HostName $20. Status $20. r15s $20. r1m $20. r15m $20. CPU_utilization $20. pg $20. ls $20. it $20. tmp $20. swp $20. mem $20.;
   input HostName $ Status $ r15s $ r1m $ r15m $ CPU_utilization $ pg $ ls $ it $ tmp $ swp $ mem $;
   run;
title "lsload Listing";
proc print data=lsload;
run;
title;

data temp1;   
   length hostname $20. cpu 8.;
   hostname="MAX"; cpu=100;
run;
data temp;
   set lsload;length CPU 8;
   cpu=compress(CPU_utilization,'%');
   label cpu="CPU %";
run;
/*data temp;
   set temp temp1;
run;*/
Axis1
	STYLE=1
	WIDTH=1
	ORDER=(0 50 100)
	MINOR= 
	(NUMBER=4
	)
;
Axis2
	STYLE=1
	WIDTH=1
;
TITLE;
TITLE1 "CPU % Utilization";
FOOTNOTE;
*FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";
* &fn footnote '<img title="PoweredBySAS-ColorHorizontal" class="cq-dd-image" alt="PoweredBySAS-ColorHorizontal" src="https://brand.sas.com/en/home/brand-assets/design-elements/logos/_jcr_content/par/styledcontainer_1011938127/par/image_2006980209.img.png/1549480759537.png">';
PROC GCHART DATA=temp
;
	VBAR3D 
	 HostName
 /
	SUMVAR=CPU
	SHAPE=BLOCK
FRAME	TYPE=SUM
SUM
	COUTLINE=BLACK
	RAXIS=AXIS1
	MAXIS=AXIS2
	LREF=1
	CREF=BLUE
	REF=100 75 50 25
;
RUN; QUIT;
TITLE;FOOTNOTE;;
options nospool;
%mend lsload;

